# Generated by Django 4.2.7 on 2023-11-22 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositproducts',
            name='user_pk',
        ),
        migrations.RemoveField(
            model_name='savingsproducts',
            name='user_pk',
        ),
    ]
